services:
  - type: web
    name: smolfile-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
buildCommand: |
  pip install -r requirements.txt
  python -m playwright install
